# Generated by Django 5.2.7 on 2025-10-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='numero',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluido')], default='', max_length=15),
        ),
    ]
